import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, AlertTriangle, CheckCircle, ArrowLeft, Gavel } from 'lucide-react';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-black text-white p-8 pt-24 flex flex-col items-center">
      <div className="max-w-4xl w-full">
        {/* Header */}
        <button onClick={() => navigate('/')} className="text-gray-500 mb-8 hover:text-white flex items-center gap-2 transition-colors">
            <ArrowLeft size={16}/> Back to Home
        </button>
        
        <div className="border-b border-gray-800 pb-8 mb-8">
            <div className="flex items-center gap-4 mb-4">
                <div className="p-4 bg-gray-900 rounded-2xl text-blue-500 border border-gray-800">
                    <FileText size={32}/>
                </div>
                <div>
                    <h1 className="text-4xl font-black uppercase italic tracking-tighter">Terms of Service</h1>
                    <p className="text-gray-500 text-sm mt-1">Last Updated: December 2025</p>
                </div>
            </div>
        </div>

        {/* Content */}
        <div className="space-y-8 text-gray-300 leading-relaxed">
            
            <section>
                <h2 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
                    <CheckCircle size={18} className="text-green-500"/> 1. Acceptance of Terms
                </h2>
                <p>
                    By accessing or using SkillForge AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use our services.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
                    <AlertTriangle size={18} className="text-yellow-500"/> 2. AI Disclaimer (Important)
                </h2>
                <p>
                    SkillForge AI provides educational content generated by Artificial Intelligence. While we strive for accuracy, AI models can occasionally produce incorrect, biased, or outdated information ("Hallucinations").
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1 text-sm text-gray-400">
                    <li><strong>No Professional Advice:</strong> The content provided is for educational purposes only and should not be considered professional career or legal advice.</li>
                    <li><strong>Code Safety:</strong> You are responsible for reviewing and testing any code generated by the platform before using it in production environments.</li>
                </ul>
            </section>

            <section>
                <h2 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
                    <Gavel size={18} className="text-purple-500"/> 3. User Conduct
                </h2>
                <p>
                    You agree not to misuse the platform. Prohibited activities include:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1 text-sm text-gray-400">
                    <li>Attempting to reverse engineer the AI prompts or backend logic.</li>
                    <li>Using the platform to generate malicious code, spam, or harassment.</li>
                    <li>Sharing your account credentials with others.</li>
                </ul>
            </section>

            <section>
                <h2 className="text-xl font-bold text-white mb-3">4. Termination</h2>
                <p>
                    We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-white mb-3">5. Limitation of Liability</h2>
                <p>
                    To the fullest extent permitted by law, SkillForge AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.
                </p>
            </section>

        </div>
        
        <div className="mt-12 pt-8 border-t border-gray-900 text-center text-gray-600 text-xs">
            © 2025 SkillForge AI Industries. All rights reserved.
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;